### ISSUE TITLE
1.20.1[1.2.5v] Hell Forge UI is missing

### ISSUE THREAD

**Issue by snlumi** [HydraOC/More-Tetra-Materials#10]
I put the battery in and charged it, but the UI doesn't display it (Note: This is a multi-server)
Fortunately, there are no problems with operation!
![2024-06-29_21 49 23](https://github.com/HydraOC/More-Tetra-Materials/assets/152872383/12d6653a-0738-4d40-b844-74697b296d2b)

**Comment by HydraOC** [comment]
Strange, I'll look into it when I have time to do so.

**Comment by HydraOC** [comment]
I've made progress on the issue, and I've seemingly gotten it to work, will upload the new version in a bit once testing is complete
