### ISSUE TITLE
Hammers cannot be made out of Mithril, Adamantium, or Pandorium.

### ISSUE THREAD

**Issue by ValerieSteel** [HydraOC/More-Tetra-Materials#12]
Title says it all. Hammer heads do not have any of the materials added by this mod as options.

**Comment by HydraOC** [comment]
I'm just setting up my IDE on my new machine right now, but I can't seem to reproduce the bug with a fresh copy of the 1.2.6 build. Can you please provide more information?

![image](https://github.com/user-attachments/assets/cd658cc8-b7af-4467-a272-5db01c988a97)

**Comment by ValerieSteel** [comment]
is 1.2.6 a version on 1.20.1?

**Comment by ValerieSteel** [comment]
Nevermind, just checked, it is. Can you check the mod's interactions with tetracelium, tetranomicon, art of forging, all the mods like that? I have a feeling one of my addons might be the issue, but I sure hope it isn't.

**Comment by HydraOC** [comment]
I'll check those mods when I get the chance

**Comment by HydraOC** [comment]
What version of Art of Forging 1.20.1 are you using? I can't get Art of Forging to launch on my end using forge or Neo forge 1.20.1. I also still cannot reproduce the bug you are seeing. Can you provide me a copy of the modpack or a mods list?

**Comment by ValerieSteel** [comment]
I'll check in a bit, not at my computer right now. I think AoF requires Tetracelium to launch. If I remember correctly, I'm just using the latest version.

**Comment by HydraOC** [comment]
I got AoF working now, but I am still unable to reproduce this issue, though there may be a mod that causes it that I can't remember the name of. Can you send me a curseforge zip so I can install your pack to verify?

**Comment by ValerieSteel** [comment]
Will a modrinth file suffice?

**Comment by ValerieSteel** [comment]
https://drive.google.com/file/d/137PxxoZ-5BjDz1hCWaZXPo-Zll9juN6o/view?usp=sharing Uploaded to google drive, because the folder was supposedly too big.

**Comment by HydraOC** [comment]
Ill check it out in a few hours when I get back from work

**Comment by ValerieSteel** [comment]
Thanks a million.

**Comment by HydraOC** [comment]
I am able to reproduce the bug now, and am going to start working on a fix for the issue after I find the cause.

**Comment by ValerieSteel** [comment]
Once again, I cannot stress this enough, THANKS A MILLION!

**Comment by HydraOC** [comment]
I genuinely cannot find the issue in the pack. I've gone through dozens of installs trying to find the root cause, but it's more than 1 specific mod that's causing the problem from my testing. Something might be f-ing with the way tiers are registered. I'm gonna try something that MIGHT fix it, but no guarentees on if it will work, since I could not find the root cause of the issue.

**Comment by HydraOC** [comment]
Considering load my f***ing tags freaks out when you load a world, it just be an unfortunate concoction of code that's compounding errors from other mods.

**Comment by ValerieSteel** [comment]
Hm. That sucks. What would you recommend I do?

**Comment by HydraOC** [comment]
Not quite sure at the moment, but apparently this issue isn't just with your pack, so I'm going to give it another shot at finding the cause.

**Comment by HydraOC** [comment]
I figured out the issue with help from Mickelus, it was a loading order issue. Uploading patched version now with a bit of flavor from the 1.3 progress I had made so far.
