### ISSUE TITLE
The material pack is displaying an error.

### ISSUE THREAD

**Issue by fszsxcylcyl** [HydraOC/More-Tetra-Materials#2]
![2024-06-03_11 15 54](https://github.com/HydraOC/More-Tetra-Materials/assets/76814391/e70d8f45-6fe3-4a6c-bfb2-5d04ba840aee)

**Comment by HydraOC** [comment]
I'll get on it shortly, just got back from work

**Comment by HydraOC** [comment]
Are you on the latest version?

**Comment by HydraOC** [comment]
![image](https://github.com/HydraOC/More-Tetra-Materials/assets/87454899/ceedd5d8-a97e-495d-b7d1-d593753b251d)
Misplaced the blockstate files during the transfer between computers, I put them back in and it fixed the issue. I'll upload the 1.2.1 file to curseforge shortly.

**Comment by HydraOC** [comment]
New file is uploaded to curseforge with the patch in place.

**Comment by fszsxcylcyl** [comment]
thanks
