### ISSUE TITLE
[bug] malformed input around byte  [1.20.1] (1.2.1v)

### ISSUE THREAD

**Issue by snlumi** [HydraOC/More-Tetra-Materials#4]
I added that mod to a pretty big modpack.
There seems to be an error in the latest version of this mod.
There is a bug that prevents other people from entering my server, but it seems to only occur in version 1.2.1 (so it was difficult to estimate the cause)
I don't know how to get crash logs.
This is because minecraft does not turn off, but only disconnects.

**Comment by HydraOC** [comment]
Can you provide me the latest.log file from the logs folder? And a copy of the modpack if possible.

**Comment by HydraOC** [comment]
A mod list would also work.

**Comment by HydraOC** [comment]
I have managed to recreate the bug and will get to work on it as time presents itself and have a multiplayer dev server set up in the future to prevent this from happening again.

**Comment by snlumi** [comment]
Something 'bad' happened recently, so I couldn't check the post.
Because Minecraft didn't turn off, I couldn't get the log file.
Thank you for your efforts to resolve the issue!

**Comment by HydraOC** [comment]
It will take a bit, since I have work today. Tommorow I can spend more time working on it since I'm off work for the weekend.

**Comment by HydraOC** [comment]
Tested and fixed the problem, will upload the patched version shortly to curseforge
